### ISSUE TITLE
ScreenLayout should take care of content size and padding

### ISSUE THREAD

**Issue by geigerzaehler** [radicle-dev/radicle-upstream#2492]
At the moment, the following styling is applied to every screen with variations.
```css
.container {
  max-width: var(--content-max-width);
  min-width: var(--content-min-width);
  padding: 0 var(--content-padding);
  margin: 0 auto;
}
```
Whenever a new screen is created this code needs to be copied. Variations in this code have led to issues like #2424.

I propose we make `ScreenLayout` responsible for this styling so that screens can be created with less overhead and we avoid common mistakes.
